### ISSUE TITLE
Better instructions on how to add new supported languages

### ISSUE THREAD

**Issue by hachesilva** [aziz/SublimeHyperClick#11]
Hi.

I have not developed a sublime plugin before and know just the basics of python so my questions might sound noob-ish.

* Do I need to add the path resolver and recompile the package or something like that or it just works by adding it and calling it from path_resolver.py? I did this and also added new languages and extensions to my package user settings an nothing happened, not sure if I'm missing something here
* Also, why is a new path resolver needed when there is a generic one already in?

**Comment by cristianl** [comment]
Closing this issue as the generic resolver has changed since the issue was opened.

The readme used to suggest creating a new path resolver, but this might not be needed in most cases. Sometimes just changing the settings is enough, but **this may cause problems on future versions of HyperClick**, so I recommend opening an issue to request a new language.

A new resolver is only necessary when the language needs special handling (e.g. sometimes the JavaScript resolver must read a npm package's *package.json*)
