### ISSUE TITLE
About Lookup Paths

### ISSUE THREAD

**Issue by berkaytheunicorn** [aziz/SublimeHyperClick#27]
Hey there,

I've been trying to get this working. Most of the case it just works but I couldn't make the below work.

```import {Button} from "/client/components/ui"```

There is a index.js file on that location.

if I write ```import {Button} from "../../components/ui" ``` it works.

I thought if I add "client" in lookup paths, it could work but no luck yet.

**Comment by anru** [comment]
Hi!

Paths which starts from `/` are being loaded from file system root. See https://nodejs.org/dist/latest-v8.x/docs/api/modules.html#modules_all_together

And importing from `lookup_paths` is working only between 3 and 4 steps described in first paragraph at link above I posted.

So your import path shouldn't starts from `/` or `.` in order to get working importing from `lookup_paths` paths
