### ISSUE TITLE
Support: Goto Definition

### ISSUE THREAD

**Issue by franciscolourenco** [aziz/SublimeHyperClick#38]
Sublime's Goto Definition does not support a `lookup_paths` configuration.

It would be great if HyperClick also supported this functionality, not only from the lines where modules are imported, but also from lines where they are used.

**Comment by cristianl** [comment]
Do you mean an improved Goto Definition system, or HyperClick jumping into the definition of a variable/module instead of its parent file?

I'm afraid I couldn't implement and maintain an alternative Goto Definition tool, and it would be outside the scope of this plugin.

May I suggest [LSP](https://github.com/sublimelsp/LSP)? It lets Sublime Text use the same code intelligence libraries that power autocomplete, go to definition/reference and symbol lists in Visual Studio Code.

It used to be a little tricky to configure (you'd have to find the equivalent language server package, install it globally, and point LSP to its executable), but now it supports plugins for a number of languages ([css/scss](https://github.com/sublimelsp/LSP-css), [js/typescript](https://github.com/sublimelsp/LSP-typescript), [vue](https://github.com/sublimelsp/LSP-vue)) which do this automatically.

**Comment by cristianl** [comment]
As for HyperClick jumping to the variable being imported (instead of just the file), I have to see if plugins can hook into ST's symbols list (or LSP, if installed).
