### ISSUE TITLE
Do you support module path alias import?

### ISSUE THREAD

**Issue by Ppang0405** [aziz/SublimeHyperClick#63]
Currently, it does not work. This package can not see the file in the import.
![Screen Shot 2020-09-23 at 22 46 37](https://user-images.githubusercontent.com/33455900/94036583-a6c20b80-fdee-11ea-8efb-dd253c884a3d.png)

**Comment by cristianl** [comment]
Currently you can do that with custom project settings.

The instructions are similar to the ones in [the new readme for version 2](https://github.com/aziz/SublimeHyperClick#project-settings) but instead of a `"lookup_paths"` array, you'll be setting an `"aliases"` object:

```json
{
	"folders":
	[
		{
			"path": "development/project"
		}
	],
	"settings": {
		"HyperClick": {
			"scopes": {
				"source.ts, source.js": {
					"aliases": {
						"@": "src"
					}
				}
			}
		}
	}
}
```

This would map `@AiwRedux/store` to `src/AiwRedux/store` for JS and TypeScript files (`"source.ts, source.js"`).

For other languages, look for the appropriate scope key in the [default settings](https://github.com/aziz/SublimeHyperClick/blob/master/HyperClick.sublime-settings) (e.g. `"source.dart"` for Dart, `"source.scss, source.sass"` for Sass)
