### ISSUE TITLE
A few config proposals

### ISSUE THREAD

**Issue by Francisc** [aziz/SublimeHyperClick#7]
Hello,

Would it be possible to add more options to customize the look of the icons?
Customizing char is great, but I'd like to control colour and size somehow.

Also, would it be possible to control appear delay on hover?

I really like this plugin, it makes me happy. Haha.

**Comment by aziz** [comment]
> would it be possible to control appear delay on hover?

No, Sublime does not provide this API, go to Sublime's Forum and ask for it. 

> Would it be possible to add more options to customize the look of the icons?
> Customizing char is great, but I'd like to control colour and size somehow.

Other than the content the look and feel of it could be customized using css inside your color scheme. see [material theme color schemes for example](https://github.com/equinusocio/material-theme/blob/develop/schemes/Material-Theme.tmTheme)

```
<key>popupCss</key>
<string><![CDATA[ 
#hyperClick {
  margin: 10px;
  padding: 20px;
}

.label-success {
  background-color: #your custom color ;
}
 ]]></string>

**Comment by Francisc** [comment]
Hey,
Thanks for the quick reply.

I'd like a way to customize that without changing the theme.
Theme-agnostic so to speak.

Too bad about the hover timeout.
Thanks for the info.

**Comment by kud** [comment]
Hello,

First of all, thank you for your great plugin, it was I needed.

Yeah it could be great to be able at least to enable or not the background.

Because depending on the icon you use, it could be annoying.

![image](https://user-images.githubusercontent.com/655838/79686636-3234e080-8242-11ea-9b7f-72f326188eec.png)

It could be great to have a setting like `annotation_background: false|true`

Thanks!
