### ISSUE TITLE
Icon beside file path is too tall?

### ISSUE THREAD

**Issue by fntn** [aziz/SublimeHyperClick#76]
See attached GIF. The icon (or its container) seems to be too tall and causing 2 lines of white space below selected line.

I think expected behaviour is that the icon is the same height as the selected line.

Has been an issue since upgrading to v2.2.0

![hyperclick](https://user-images.githubusercontent.com/785590/98993809-da83fc80-2526-11eb-956f-8821492a3ddc.gif)

**Comment by jfcherng** [comment]
Probably related to https://github.com/aziz/SublimeHyperClick/commit/b72021b57d944fac0d505ab1059270cd4d159574#diff-f9206110fca417478fb172413816a54a3185c7bb9bb2999e3d6bd15793698be6L14-L15

**Comment by cristianl** [comment]
Sorry, I cannot reproduce this. Can you clone and manually install https://github.com/cristianl/SublimeHyperClick/tree/issue76-html-margin to check if @jfcherng's [suggestion](https://github.com/aziz/SublimeHyperClick/issues/76#issuecomment-726495273) works?

(Package Control can install packages from repo URLs, but for HyperClick this seems to trigger a settings bug and icons are never displayed, probably because the repo is named `SublimeHyperClick` and it looks for a package named `HyperClick`)

**Comment by fntn** [comment]
Hi, I didn't get a chance to try the suggestion above but the issue has been fixed with the latest update. Many thanks!
